export const schemas = {
  players: [
    ["id", "Int", "The player's ID"],
    ["name", "String", "The player's name"],
    ["fullname", "String", "The player's full name"],
    ["birth", "Object", "The player's country, place and date of birth."],
    ["nationalities", "Array", "All the nationalities of the player"],
    [
      "national_team",
      "Object",
      "The national team the player play for in FIFA/UEFA competitions",
    ],
    ["weight", "Int", "The player's weight"],
    ["height", "Int", "The player's height"],
    ["position", "Array", "The player's positions on the field"],
    ["strong_foot", "String", "The player's strongest foot. May be both."],
    ["fee", "Array", "Contains objects describing arrival and departure fees"],
    [
      "period",
      "Array",
      "Contains Objects describing the periods the player played for the team",
    ],
    ["number", "Array", "The player's jersey numbers in the team"],
    ["matches", "Int", "The number of matches played with the team"],
    ["goals", "Int", "The number of goals with the team"],
    ["assists", "Int", "The number of assists with the team"],
    ["previous_club", "Array", "The previous club of the player"],
    [
      "next_club",
      "Array",
      "The club the player played for after leaving the team",
    ],
    ["trophies", "Array", "All the ids of the trophies won with the team."],
    ["photo", "String", "A photo to describe the player."],
    ["url", "String", "The link to the player's URL endpoint."],
  ],
  coaches: [
    ["id", "Int", "The coach's ID"],
    ["name", "Object", "The coach's name"],
    ["fullname", "String", "The coach's full name"],
    ["birth", "Object", "The coach's country, place and date of birth. "],
    ["nationalities", "Array", "All the nationalities of the coach"],
    [
      "period",
      "Array",
      "Contains objects describing the periods he was the coach of the club",
    ],
    [
      "stats",
      "Object",
      "Contains the stats by competitions the coach had with the team",
    ],
    ["trophies", "Array", "All the ids of the trophies won with the team."],
    ["photo", "String", "A photo to describe the coach."],
    ["url", "String", "The link to the coach's URL endpoint."],
  ],
  presidents: [
    ["id", "Int", "The president's ID."],
    ["name", "Object", "The president's name."],
    ["fullname", "String", "The president's full name."],
    [
      "birth",
      "Object",
      "Contains the president's country, place and date of birth. ",
    ],
    ["nationalities", "Array", "All the nationalities of the president. "],
    [
      "period",
      "Array",
      "Contains objects describing the periods he was president of the club",
    ],
    ["trophies", "Array", "All the ids of the trophies won with the team."],
    ["photo", "String", "A photo to describe the president."],
    ["url", "String", "The link to the president's URL endpoint."],
  ],
  owners: [
    ["id", "Int", "The owner's ID"],
    ["name", "Object", "The owner's name"],
    [
      "country",
      "Array",
      "The country where the owner's headquarter is located in",
    ],
    [
      "period",
      "Array",
      "Contains objects describing the periods he owned the team",
    ],
    ["photo", "String", "A photo of the owner."],
    ["url", "String", "The link to the owner's URL endpoint."],
  ],
  matches: [
    ["date", "Date", "The date of the match"],
    ["season", "ObjectID", "The id of the season"],
    ["competition", "String", "The name of the competition"],
    ["round", "String", "The round of the match during the competition"],
    ["stadium", "String", "The stadium in which the match was played"],
    ["vs_team", "String", "The away team"],
    ["at_home", "Boolean", "Indicate if it was at home"],
    ["players", "Array", "All the ids of the players who played"],
    ["score", "String", "The result of the match"],
    [
      "goals",
      "Array",
      "Object containing the minute and the ids of the scorer and passer of each goals",
    ],
    ["url", "String", "The link to the match's URL endpoint."],
  ],
  seasons: [
    ["id", "Int", "The id of the season"],
    ["date", "String", "The date of the season"],
    ["results", "Object", "All the results of the season by competitions"],
    [
      "mercato",
      "Object",
      "All the players transfered during the transfer windows of the season",
    ],
  ],
  trophies: [
    ["id", "Int", "The id of the trophy"],
    ["season", "Array", "The id of the season"],
    ["competition", "String", "The name of the won competition"],
    ["domestic", "String", "Indicate if it is a domestic trophy or not."],
    ["date", "Date", "The date the trophy was won"],
  ],
};
